# -*- coding: utf-8 -*-

from odoo import api, fields, models, _


class StockMoveLine(models.Model):
    _inherit = "stock.move.line"

    picking_code = fields.Selection(related="move_id.picking_code", string='Type of Operation')
    equipment_id = fields.Many2one('maintenance.equipment',related="lot_id.equipment_id",readonly=True,string="Equipment",help="The equipment generated by this stock move line.")
    create_equipment = fields.Boolean(string="Create Equipment",help="select this to create a new equipment automatically once the stock picking validated")
    is_equipment = fields.Boolean(string="Is equipment?", related="product_id.is_equipment")

    @api.model
    def create(self, vals):
        """
        Override stock move line create method to set Create Equipment to True in move line
        :param vals:
        :return:
        """
        ml = super(StockMoveLine, self).create(vals)
        if ml and ml.product_id and ml.product_id.is_equipment and ml.move_id.picking_type_id.code == 'incoming':
            ml.is_equipment = ml.product_id.is_equipment
        return ml
